#[derive(Debug, Clone, PartialEq)]
pub enum Language {
    English,
    German,
}

impl Language {
    pub fn name(&self) -> &str {
        match self {
            Language::English => "English",
            Language::German => "Deutsch",
        }
    }

    pub fn code(&self) -> &str {
        match self {
            Language::English => "en",
            Language::German => "de",
        }
    }

    pub fn from_code(code: &str) -> Self {
        match code {
            "de" => Language::German,
            _ => Language::English,
        }
    }
}

pub struct Locale {
    pub language: Language,
}

impl Locale {
    pub fn new(language: Language) -> Self {
        Locale { language }
    }

    pub fn t(&self, key: &str) -> &'static str {
        match self.language {
            Language::English => en(key),
            Language::German => de(key),
        }
    }
}

fn en(key: &str) -> &'static str {
    match key {
        "app.title" => "BibleDesk",
        "tab.reader" => "Reader",
        "tab.search" => "Search",
        "tab.plans" => "Reading Plans",
        "tab.saved" => "Saved Verses",
        "tab.flashcards" => "Flashcards",
        "tab.settings" => "Settings",
        "reader.select_book" => "Select Book",
        "reader.chapter" => "Chapter",
        "reader.translation" => "Translation",
        "reader.load" => "Load Chapter",
        "reader.loading" => "Loading...",
        "reader.save_verse" => "Save Verse",
        "reader.unsave_verse" => "Unsave Verse",
        "reader.add_flashcard" => "Add to Flashcards",
        "reader.previous" => "← Previous",
        "reader.next" => "Next →",
        "reader.no_chapter" => "Select a book and chapter to begin reading.",
        "reader.download_book" => "Download Book",
        "reader.downloading_book" => "Downloading...",
        "reader.book_downloaded" => "Book downloaded!",
        "reader.verse_context_save" => "Save Verse",
        "reader.verse_context_unsave" => "Remove from Saved",
        "reader.verse_context_flashcard" => "Add to Flashcards",
        "reader.mark" => "Mark",
        "reader.mark_yellow" => "🟡 Yellow",
        "reader.mark_green" => "🟢 Green",
        "reader.mark_blue" => "🔵 Blue",
        "reader.mark_pink" => "🌸 Pink",
        "reader.clear_mark" => "✕ Clear Mark",
        "reader.marker_off" => "Off",
        "reader.marker_mode" => "Marker:",
        "search.placeholder" => "Search for words, phrases, or verse references...",
        "search.button" => "Search",
        "search.results" => "Results",
        "search.no_results" => "No results found. Download some chapters first.",
        "search.filter_translation" => "Filter by translation",
        "search.all_translations" => "All translations",
        "plans.title" => "Reading Plans",
        "plans.new" => "New Plan",
        "plans.name_placeholder" => "Plan name...",
        "plans.create" => "Create",
        "plans.delete" => "Delete",
        "plans.add_chapter" => "Add Chapter",
        "plans.no_plans" => "No reading plans yet. Create one!",
        "plans.book" => "Book",
        "plans.chapter" => "Chapter",
        "plans.date" => "Date (optional, YYYY-MM-DD)",
        "plans.add" => "Add",
        "plans.progress" => "Progress",
        "plans.completed" => "Completed",
        "plans.mark_done" => "Done",
        "plans.mark_undone" => "Undo",
        "saved.title" => "Saved Verses",
        "saved.note" => "Note",
        "saved.save_note" => "Save Note",
        "saved.delete" => "Delete",
        "saved.no_saved" => "No saved verses yet. Save verses from the Reader.",
        "saved.filter" => "Filter by translation",
        "flashcards.title" => "Flashcards",
        "flashcards.add_from_saved" => "Add from Saved Verses",
        "flashcards.mode_ref" => "Reference → Verse",
        "flashcards.mode_verse" => "Verse → Reference",
        "flashcards.show_reference" => "Reference",
        "flashcards.show_verse" => "Verse",
        "flashcards.your_answer" => "Your answer...",
        "flashcards.check" => "Check",
        "flashcards.correct" => "✓ Correct!",
        "flashcards.incorrect" => "✗ Incorrect",
        "flashcards.next_card" => "Next Card",
        "flashcards.no_cards" => "No flashcards yet. Add some from saved verses.",
        "flashcards.stats" => "Stats",
        "flashcards.successes" => "Successes",
        "flashcards.failures" => "Failures",
        "flashcards.delete" => "Delete Card",
        "flashcards.cards" => "Cards",
        "flashcards.review" => "Study",
        "flashcards.back_to_list" => "← Back to Cards",
        "settings.title" => "Settings",
        "settings.language" => "Interface Language",
        "settings.default_translation" => "Default Translation",
        "settings.theme" => "Theme",
        "settings.theme_light" => "Light",
        "settings.theme_dark" => "Dark",
        "settings.cache_info" => "Cache is stored in the local SQLite database.",
        "settings.save" => "Save Settings",
        "settings.saved" => "Settings saved!",
        _ => "",
    }
}

fn de(key: &str) -> &'static str {
    match key {
        "app.title" => "BibleDesk",
        "tab.reader" => "Leser",
        "tab.search" => "Suche",
        "tab.plans" => "Lesepläne",
        "tab.saved" => "Gespeicherte Verse",
        "tab.flashcards" => "Karteikarten",
        "tab.settings" => "Einstellungen",
        "reader.select_book" => "Buch auswählen",
        "reader.chapter" => "Kapitel",
        "reader.translation" => "Übersetzung",
        "reader.load" => "Kapitel laden",
        "reader.loading" => "Laden...",
        "reader.save_verse" => "Vers speichern",
        "reader.unsave_verse" => "Vers entfernen",
        "reader.add_flashcard" => "Zu Karteikarten hinzufügen",
        "reader.previous" => "← Vorheriges",
        "reader.next" => "Nächstes →",
        "reader.no_chapter" => "Wählen Sie ein Buch und Kapitel zum Lesen.",
        "reader.download_book" => "Buch herunterladen",
        "reader.downloading_book" => "Herunterladen...",
        "reader.book_downloaded" => "Buch heruntergeladen!",
        "reader.verse_context_save" => "Vers speichern",
        "reader.verse_context_unsave" => "Aus Gespeicherten entfernen",
        "reader.verse_context_flashcard" => "Zu Karteikarten hinzufügen",
        "reader.mark" => "Markieren",
        "reader.mark_yellow" => "🟡 Gelb",
        "reader.mark_green" => "🟢 Grün",
        "reader.mark_blue" => "🔵 Blau",
        "reader.mark_pink" => "🌸 Rosa",
        "reader.clear_mark" => "✕ Markierung entfernen",
        "reader.marker_off" => "Aus",
        "reader.marker_mode" => "Markierung:",
        "search.placeholder" => "Wörter, Phrasen oder Versreferenzen suchen...",
        "search.button" => "Suchen",
        "search.results" => "Ergebnisse",
        "search.no_results" => "Keine Ergebnisse. Laden Sie zuerst einige Kapitel herunter.",
        "search.filter_translation" => "Nach Übersetzung filtern",
        "search.all_translations" => "Alle Übersetzungen",
        "plans.title" => "Lesepläne",
        "plans.new" => "Neuer Plan",
        "plans.name_placeholder" => "Planname...",
        "plans.create" => "Erstellen",
        "plans.delete" => "Löschen",
        "plans.add_chapter" => "Kapitel hinzufügen",
        "plans.no_plans" => "Noch keine Lesepläne. Erstellen Sie einen!",
        "plans.book" => "Buch",
        "plans.chapter" => "Kapitel",
        "plans.date" => "Datum (optional, JJJJ-MM-TT)",
        "plans.add" => "Hinzufügen",
        "plans.progress" => "Fortschritt",
        "plans.completed" => "Abgeschlossen",
        "plans.mark_done" => "Fertig",
        "plans.mark_undone" => "Rückgängig",
        "saved.title" => "Gespeicherte Verse",
        "saved.note" => "Notiz",
        "saved.save_note" => "Notiz speichern",
        "saved.delete" => "Löschen",
        "saved.no_saved" => "Noch keine gespeicherten Verse. Speichern Sie Verse aus dem Leser.",
        "saved.filter" => "Nach Übersetzung filtern",
        "flashcards.title" => "Karteikarten",
        "flashcards.add_from_saved" => "Aus gespeicherten Versen hinzufügen",
        "flashcards.mode_ref" => "Referenz → Vers",
        "flashcards.mode_verse" => "Vers → Referenz",
        "flashcards.show_reference" => "Referenz",
        "flashcards.show_verse" => "Vers",
        "flashcards.your_answer" => "Ihre Antwort...",
        "flashcards.check" => "Prüfen",
        "flashcards.correct" => "✓ Richtig!",
        "flashcards.incorrect" => "✗ Falsch",
        "flashcards.next_card" => "Nächste Karte",
        "flashcards.no_cards" => "Noch keine Karteikarten. Fügen Sie welche aus gespeicherten Versen hinzu.",
        "flashcards.stats" => "Statistik",
        "flashcards.successes" => "Erfolge",
        "flashcards.failures" => "Fehlversuche",
        "flashcards.delete" => "Karte löschen",
        "flashcards.cards" => "Karten",
        "flashcards.review" => "Lernen",
        "flashcards.back_to_list" => "← Zurück zur Liste",
        "settings.title" => "Einstellungen",
        "settings.language" => "Sprache der Benutzeroberfläche",
        "settings.default_translation" => "Standardübersetzung",
        "settings.theme" => "Design",
        "settings.theme_light" => "Hell",
        "settings.theme_dark" => "Dunkel",
        "settings.cache_info" => "Cache wird in der lokalen SQLite-Datenbank gespeichert.",
        "settings.save" => "Einstellungen speichern",
        "settings.saved" => "Einstellungen gespeichert!",
        _ => "",
    }
}
